export {
  ACTIVITY_CODES as COURSE_CODES,
  type ActivityCode as CourseCode,
  activityCodeValidator as courseCodeValidator,
  ACTIVITY_CODES,
  type ActivityCode,
  type ActivityCatalogEntry as CourseCatalogEntry,
  type Agency,
  ACTIVITY_CATALOG as COURSE_CATALOG,
  ACTIVITY_DISPLAY_LABELS as COURSE_DISPLAY_LABELS,
  ALL_COURSE_CODES,
  activityLabel as courseLabel,
  getActivityByCode as getCourseByCode,
  getActivitiesForAgency as getCoursesForAgency,
  COMBO_COURSES,
} from '../../../convex/shared/activityCatalog'
