export {
  SCUBAPRO_WETSUITS,
  SCUBAPRO_BCDS,
  AQUALUNG_WETSUITS,
  AQUALUNG_BCDS,
  MARES_WETSUITS,
  MARES_BCDS,
  ALL_GEAR_SIZING,
  MANUFACTURERS,
  GEAR_TYPES,
  GEAR_TYPE_LABELS,
  FIN_SIZE_SYSTEMS,
  FIN_SIZES_EU,
  FIN_SIZES_US,
  FIN_SIZES_CM,
  FIN_SIZES_LETTER,
  finSizesFor,
  isMatrixGearType,
  type GearSizingEntry,
  type FinSizingEntry,
  type Manufacturer,
  type GearType,
  type FinSizeSystem,
  type MatrixGearType,
} from '../../../convex/shared/gearSizing'
