/**
 * Single source of truth for SSR :root derived tokens (status/bg/border, badges,
 * alerts, calendar) emitted to src/app/globals-status-derived.css.
 * Base hex tokens stay in globals-theme.css; ThemeProvider injects bases at runtime.
 */

const STATUS_KEYS_WITH_DERIVED = [
  "active",
  "draft",
  "upcoming",
  "completed",
  "cancelled",
  "urgent",
] as const;

/** Emits globals-status-derived.css body (excluding file banner). */
export function renderGlobalsStatusDerivedCss(): string {
  const lines: string[] = [];

  lines.push(`  /* Status derived — base hex tokens in globals-theme.css`);
  lines.push(`     Runtime: ThemeProvider overrides bases; these mix() against injected values. */`);

  for (const key of STATUS_KEYS_WITH_DERIVED) {
    const base = `--color-status-${key}`;
    lines.push(`  --color-status-${key}-bg: color-mix(`);
    lines.push(`    in srgb,`);
    lines.push(`    var(${base}) calc(var(--opacity-subtle) * 100%),`);
    lines.push(`    transparent`);
    lines.push(`  );`);
    lines.push(`  --color-status-${key}-border: color-mix(`);
    lines.push(`    in srgb,`);
    lines.push(`    var(${base}) 50%,`);
    lines.push(`    transparent`);
    lines.push(`  );`);
  }

  lines.push(`  /* Badge semantic tints — derived from base palette, skin-switchable via base color */`);
  lines.push(`  --color-badge-success-bg: color-mix(`);
  lines.push(`    in srgb,`);
  lines.push(`    var(--color-success) 25%,`);
  lines.push(`    transparent`);
  lines.push(`  );`);
  lines.push(`  --color-badge-success-border: color-mix(`);
  lines.push(`    in srgb,`);
  lines.push(`    var(--color-success) 30%,`);
  lines.push(`    transparent`);
  lines.push(`  );`);
  lines.push(`  --color-badge-warning-bg: color-mix(`);
  lines.push(`    in srgb,`);
  lines.push(`    var(--color-warning) 25%,`);
  lines.push(`    transparent`);
  lines.push(`  );`);
  lines.push(`  --color-badge-warning-border: color-mix(`);
  lines.push(`    in srgb,`);
  lines.push(`    var(--color-warning) 30%,`);
  lines.push(`    transparent`);
  lines.push(`  );`);
  lines.push(`  --color-badge-destructive-bg: color-mix(`);
  lines.push(`    in srgb,`);
  lines.push(`    var(--color-destructive) 25%,`);
  lines.push(`    transparent`);
  lines.push(`  );`);
  lines.push(`  --color-badge-destructive-border: color-mix(`);
  lines.push(`    in srgb,`);
  lines.push(`    var(--color-destructive) 30%,`);
  lines.push(`    transparent`);
  lines.push(`  );`);
  lines.push(`  --color-badge-info-bg: color-mix(`);
  lines.push(`    in srgb,`);
  lines.push(`    var(--color-secondary) 25%,`);
  lines.push(`    transparent`);
  lines.push(`  );`);
  lines.push(`  --color-badge-info-border: color-mix(`);
  lines.push(`    in srgb,`);
  lines.push(`    var(--color-secondary) 30%,`);
  lines.push(`    transparent`);
  lines.push(`  );`);

  lines.push(`  --color-alert-error-bg: color-mix(`);
  lines.push(`    in srgb,`);
  lines.push(`    var(--color-destructive) 8%,`);
  lines.push(`    transparent`);
  lines.push(`  );`);
  lines.push(`  --color-alert-error-border: color-mix(`);
  lines.push(`    in srgb,`);
  lines.push(`    var(--color-destructive) 30%,`);
  lines.push(`    transparent`);
  lines.push(`  );`);
  lines.push(`  --color-alert-warning-bg: color-mix(`);
  lines.push(`    in srgb,`);
  lines.push(`    var(--color-warning) 8%,`);
  lines.push(`    transparent`);
  lines.push(`  );`);
  lines.push(`  --color-alert-warning-border: color-mix(`);
  lines.push(`    in srgb,`);
  lines.push(`    var(--color-warning) 40%,`);
  lines.push(`    transparent`);
  lines.push(`  );`);

  lines.push(`  /* Blocked — operational constraint, uses urgent color (icon differentiates) */`);
  lines.push(`  --color-blocked-bg: color-mix(`);
  lines.push(`    in srgb,`);
  lines.push(`    var(--color-blocked) calc(var(--opacity-subtle) * 100%),`);
  lines.push(`    transparent`);
  lines.push(`  );`);
  lines.push(`  --color-blocked-border: color-mix(`);
  lines.push(`    in srgb,`);
  lines.push(`    var(--color-blocked) 50%,`);
  lines.push(`    transparent`);
  lines.push(`  );`);

  lines.push(`  /* Calendar date watermarks — opacity scales per luminance class */`);
  lines.push(`  --color-date-watermark: color-mix(`);
  lines.push(`    in srgb,`);
  lines.push(`    var(--color-text-primary) calc(var(--opacity-watermark) * 100%),`);
  lines.push(`    transparent`);
  lines.push(`  );`);
  lines.push(`  --color-date-blocked: var(--color-text-secondary);`);

  const inner = lines.join("\n");
  return `/* GENERATED by src/scripts/generate-globals-derived-css.ts — do not edit by hand. */

:root {
${inner}
}
`;
}
