export const ErrorCode = {
  UNAUTHENTICATED: 'UNAUTHENTICATED',
  FORBIDDEN: 'FORBIDDEN',

  NOT_FOUND: 'NOT_FOUND',

  VALIDATION: 'VALIDATION',
  INVALID_STATUS: 'INVALID_STATUS',
  INVALID_STATE: 'INVALID_STATE',
  INVALID_TRANSITION: 'INVALID_TRANSITION',
  INVALID_INPUT: 'INVALID_INPUT',

  BOOKING_CLOSED: 'BOOKING_CLOSED',
  BLOCKED_DATE: 'BLOCKED_DATE',
  MAX_DIVES_EXCEEDED: 'MAX_DIVES_EXCEEDED',
  PAST_DATE: 'PAST_DATE',
  TOO_EARLY: 'TOO_EARLY',
  REVERT_WINDOW_EXPIRED: 'REVERT_WINDOW_EXPIRED',

  CONFLICT: 'CONFLICT',
  ORPHANED_RESERVATION: 'ORPHANED_RESERVATION',
  MISSING_SNAPSHOT: 'MISSING_SNAPSHOT',
  MISSING_SNAPSHOT_ON_RELEASE: 'MISSING_SNAPSHOT_ON_RELEASE',
  CONFIRMED_RESERVATION_EXISTS: 'CONFIRMED_RESERVATION_EXISTS',

  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  FORMS_INCOMPLETE: 'FORMS_INCOMPLETE',

  PROFILE_INCOMPLETE: 'PROFILE_INCOMPLETE',
  RESOURCES_INCOMPLETE: 'RESOURCES_INCOMPLETE',
  DUPLICATE_ROLE: 'DUPLICATE_ROLE',
  ROLE_NOT_HELD: 'ROLE_NOT_HELD',
  LAST_ROLE: 'LAST_ROLE',

  SNAPSHOT_UNDERFLOW: 'SNAPSHOT_UNDERFLOW',
  SNAPSHOT_DOUBLE_WRITE: 'SNAPSHOT_DOUBLE_WRITE',
  SNAPSHOT_FIELD_IMMUTABLE: 'SNAPSHOT_FIELD_IMMUTABLE',

  INVARIANT_VIOLATION: 'INVARIANT_VIOLATION',

  CAPABILITY_GAP: 'CAPABILITY_GAP',
  TEACHING_LANGUAGES_REQUIRED: 'TEACHING_LANGUAGES_REQUIRED',

  RATE_LIMITED: 'RATE_LIMITED',
} as const;
