/**
 * Canonical error codes for ConvexError({ code }) payloads.
 * Single source of truth — import instead of using raw strings.
 */
export const ErrorCode = {
  // Auth
  UNAUTHENTICATED: 'UNAUTHENTICATED',
  FORBIDDEN: 'FORBIDDEN',

  // Lookup
  NOT_FOUND: 'NOT_FOUND',

  // Validation
  VALIDATION: 'VALIDATION',
  INVALID_STATUS: 'INVALID_STATUS',
  INVALID_STATE: 'INVALID_STATE',
  INVALID_TRANSITION: 'INVALID_TRANSITION',
  INVALID_INPUT: 'INVALID_INPUT',

  // Booking lifecycle
  BOOKING_CLOSED: 'BOOKING_CLOSED',
  BLOCKED_DATE: 'BLOCKED_DATE',
  MAX_DIVES_EXCEEDED: 'MAX_DIVES_EXCEEDED',
  PAST_DATE: 'PAST_DATE',
  TOO_EARLY: 'TOO_EARLY',
  REVERT_WINDOW_EXPIRED: 'REVERT_WINDOW_EXPIRED',

  // Inventory / reservations
  CONFLICT: 'CONFLICT',
  ORPHANED_RESERVATION: 'ORPHANED_RESERVATION',
  MISSING_SNAPSHOT: 'MISSING_SNAPSHOT',
  MISSING_SNAPSHOT_ON_RELEASE: 'MISSING_SNAPSHOT_ON_RELEASE',
  CONFIRMED_RESERVATION_EXISTS: 'CONFIRMED_RESERVATION_EXISTS',

  // Portal
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  FORMS_INCOMPLETE: 'FORMS_INCOMPLETE',

  // Profile / roles
  PROFILE_INCOMPLETE: 'PROFILE_INCOMPLETE',
  COVERAGE_INCOMPLETE: 'COVERAGE_INCOMPLETE',
  DUPLICATE_ROLE: 'DUPLICATE_ROLE',
  ROLE_NOT_HELD: 'ROLE_NOT_HELD',

  // Invariant protection
  INVARIANT_VIOLATION: 'INVARIANT_VIOLATION',

  // Rate limiting
  RATE_LIMITED: 'RATE_LIMITED',
} as const;
